### ISSUE TITLE
Machine leesbare specificatie van DCAT-AP-NL

### ISSUE THREAD

**Issue by Bakkej** [Geonovum/dcat2-ap-nl#26]
Om met dcat-ap-nl te werken is het waardevol om ook een data specificatie aan te bieden vanuit de werkgroep. Dit zie je ook bij de SEMIC werkgroepen, bijvoorbeeld: https://github.com/SEMICeu/DCAT-AP/blob/master/releases/2.1.1/dcat-ap_2.1.1_shacl_shapes.ttl
Hiermee zorgen we ervoor dat iedereen data op dezelfde manier valideert. Semic gebruikt shacl om de data specificatie op te stellen. Dit maken ze op basis van een UML model, zie ook de [style-guide](https://semiceu.github.io/style-guide/1.0.0/arhitectural-clarifications.html#sec:data-specification-and-artefact-types). 
Dit kunnen wij ook doen door DCAT-AP-NL in MIM uit te drukken en hiermee vervolgens een shacl-model te genereren. 
Dit is bijvoorbeeld ook voor [IMX-geo](https://github.com/Geonovum/IMX-Geo) gedaan. 

Deze issue is ook gerelateerd aan https://github.com/Geonovum/dcat2-ap-nl/issues/1

**Comment by keestrautwein** [comment]
Ik ben helemaal voor. Uit de praktijk: Logius is bezig met de nieuwe Begrippenkaderstandaard waarbij m.n. het SHACL bestand dat is gebruikt voor de specificatie van de standaard direct heel waardevol is en veel tijd bespaard. Dat zal ook zo zijn voor partijen die met het DCAT-NL profiel aan de slag willen

**Comment by keestrautwein** [comment]
Zie mijn commentaar in #1

**Comment by idevisser** [comment]
Zie voor de discussie over dit onderwerp issue #1
